# Generated by Django 4.0.3 on 2022-03-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.CharField(max_length=100)),
                ('checkin_month', models.CharField(max_length=10)),
                ('checkin_year', models.CharField(max_length=10)),
                ('checkin_day', models.CharField(max_length=10)),
                ('checkout', models.DateField()),
                ('flat', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('income', models.FloatField()),
            ],
        ),
    ]
